apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: nginx-replicaset
 labels:
  app: nginx
  type: frontend
spec:
 template:
  metadata:
   labels:
    app: nginx-pod
    type: frontend
   name: nginx-pod
  spec:
   containers:
   - image: nginx:1.24
     name: nginx-pod
   restartPolicy: Always
 replicas: 3
 selector:
  matchLabels:
   type: frontend
